### ISSUE TITLE
Cannot find module 'velocity-react' 

### ISSUE THREAD

**Issue by hckrmoon** [UYEONG/react-doldolyi#4]
ERROR in ./~/react-doldolyi/dist/Oval.js
Module not found: Error: Cannot resolve module 'velocity-react'

**Comment by UYEONG** [comment]
plz, RR.

**Comment by hckrmoon** [comment]
Sorry, I can't get the meaning of 'RR'

**Comment by UYEONG** [comment]
oh, sorry... RR is a typing error. that's mean PR
